# Generated by Django 6.0.3 on 2026-03-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='', upload_to='book_covers/'),
            preserve_default=False,
        ),
    ]
