# Generated by Django 6.0.3 on 2026-06-19 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_rename_user_id_address_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='trancation_id',
            new_name='transaction_id',
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='ecom.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='ecom.genere'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='genere',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
