# Generated by Django 6.0.3 on 2026-06-19 15:26

import ecom.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_rename_trancation_id_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='books/cover', validators=[ecom.validators.validate_image_extension]),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_must_be_greater_than_zero'),
        ),
    ]
