# Generated by Django 6.0.3 on 2026-07-01 06:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('FLAT', 'Flat Amount'), ('PERCENTAGE', 'Percentage')], default='FLAT', max_length=15),
        ),
        migrations.AddField(
            model_name='coupon',
            name='first_order_only',
            field=models.BooleanField(default=False, help_text="Check if coupon is only valid for user's first completed order"),
        ),
        migrations.AddField(
            model_name='coupon',
            name='free_shipping',
            field=models.BooleanField(default=False, help_text='Check if this coupon provides free shipping'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount allowed for percentage type', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order subtotal to apply this coupon', max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of times a single user can use this coupon', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of times this coupon can be used globally', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, help_text='Flat amount or percentage value', max_digits=10),
        ),
    ]
